server:
  port: 8081

spring:
  application:
    name: myWeb
  thymeleaf:
    check-template-location: true
    content-type: text/html
    enabled: true
    cache: false
    prefix: classpath:/templates/
    suffix: .html

zuul:
  #prefix: /mySpringCloud
  routes:
    myService1route:
      serviceId: myService1
      path: /myService1Url/**
 
eureka:
  instance:
    instance-id: myWeb_dev_instance
    prefer-ip-address: true     #访问路径可以显示IP地址 
    #ip-address: localhost
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/      

ribbon:
  ReadTimeout: 10000  
  ConnectTimeout: 10000
  MaxAutoRetries: 3

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 10000
                        
info: 
  app.name: myWeb-springCloud
  company.name: www.surichard.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
